config/routes.rb
Rails.application.routes.draw do
  

  devise_for :users, only: :omniauth_callbacks, controllers: {omniauth_callbacks: 'user/omniauth_callbacks'}

  scope "(:locale)", :locale => /#{I18n.available_locales.join("|")}/ do  


    devise_for :users, skip: [:registrations, :omniauth_callbacks], controllers: {confirmations: 'user/confirmations'}, 
                        path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register', 
                                               password: 'password', confirmation: 'account-activation'}
    
    devise_scope :user do      
      # registrations
      put    '/users',  to: 'user/registrations#update'
      delete '/users',  to: 'user/registrations#destroy'
      post   '/users',  to: 'user/registrations#create'
      get    '/register', to: 'user/registrations#new',    as: :new_user_registration
      get    '/users/:id/edit',  to: 'user/registrations#edit',   as: :edit_user_registration
      patch  '/users',  to: 'user/registrations#update', as: :user_registration
      get    '/users/cancel', to: 'user/registrations#cancel', as: :cancel_user_registration 
    end


    resources :users, only: [:show]
    resources :listings
    resources :buys, controller:"listings", type:"Buy"
    resources :sells, controller:"listings", type:"Sell"
    resources :contactmsg, only: [:listing_contact]

    post '/contact', to: 'contacts#listing_contact'


    root 'listings#index'

    get '/about' => "pages#about"
    

  end #locale scope
  
end

app/models/listing.rb
class Listing < ApplicationRecord
  
  belongs_to :user
  has_one_attached :image

  validates :user_id, presence: true
  validates :type, type_check: true
  validates :expires, expiration_date: true
  validates :title, presence: true, length: {maximum:50}
  validates :description, presence: true, length:{minimum: 40}
  validates :city, length: {maximum: 100}
  validates :state, length: {maximum: 50}
  validates :country, length: {maximum: 100}
  validates :image, content_type: {in: %w[image/jpeg image/gif image/png], message: :wrongimgformat},
                                  size: {less_than: 10.megabytes, message: :imagetoobig}

  default_scope -> {order(created_at: :desc)}

  def self.listing_types
    %w(Buy Sell)
  end


  def owned_by?(user)
    self.user_id == (user.try(:id) || user)
  end


  def set_expirydate
    self.expires = Date.today() + 14.days
  end

end
  

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :owned_by, only: [:edit, :update, :destroy]

  layout 'nobanner', :only => [:index]

  def index
    #Use listingtype so index action can work on just all buys, 
    #or just all sells, or all listings either way.
    listingtype= listing_type.safe_constantize
    #Only show listings that have not expired
    @listings = listingtype.where("expires > ?", Date.today())
  end

  
  def show
    @contactmsg = Contactmsg.new
  end

 
  def new
    @listing = Listing.new
  end

 
  def edit
  end


  def create
  
    @listing = current_user.listings.build(listing_params)
    #Automatically set expiry date to 2 weeks from now.
    @listing.set_expirydate

    if @listing.save
      flash[:success] = t 'listingcreated'
      redirect_to @listing
    else
      flash.now[:alert] =t 'listingnotcreated'
      render 'listings/new'
    end
  end

  def update  
    if @listing.update(listing_params)
      flash[:success] = t 'listingupdated'
      redirect_to @listing.becomes(Listing)
    else
      flash.now[:alert] = t 'listingnotupdated'
      render :edit
    end

  end

  def destroy
    @listing.destroy
    redirect_to listings_url, notice: (t 'listingdestroyed')
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    def listing_type
      listing_type = Listing.listing_types.include?(params[:type]) ?  params[:type] : "Listing"
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(listing_type.underscore.to_sym).permit(:type, :city, :state, :country, :title, :description, :image, :user_id)
    end

    def owned_by
      redirect_to(user_path(current_user)) unless ( (current_user.id == @listing.user_id) || current_user.admin)
    end
end

app/helpers/listings_helper.rb
module ListingsHelper
    def display_image(listing)
        link_to listing do
          if listing.image.attached?
            image_tag listing.image, style: 'width: 200px; max-height: 140px;', class: 'img-thumbnail'
          else
            image_tag "azteca.png", class: 'img-thumbnail'
          end
        end
    end

    def display_card_image(listing)
        if listing.image.attached?
            image_tag listing.image, class: 'grid-image card-img-top'
        else
            image_tag "azteca.png", class: 'grid-image card-img-top'
        end  
    end

end

app/views/listings/_form.html.haml
= form_for @listing do |f|
  - if @listing.errors.any?
    #error_explanation
      %h5
        = pluralize(@listing.errors.count, (t 'error'), locale: I18n.locale) + " " + t('prohibitedlisting', count: @listing.errors.count)
      %ul
        - @listing.errors.full_messages.each do |message|
          %li= message


  .card.card-body


      
    
    .row.mb-5
      .col-4.col-form-label
        =t 'selecttype'
      .col-8
        .btn-group.d-flex.btn-group-toggle.w-100{"data-toggle" => "buttons"}
          %label.btn.btn-block.btn-outline-primary.w-100.active
            = f.radio_button :type, 'Sell', checked: "checked"
            =t 'offering'
          %label.btn.btn-outline-orange.w-100
            = f.radio_button :type, 'Buy'
            =t 'seeking'

    
    .form-group
      = f.label :title, (t 'title')
      = f.text_field :title, class: 'form-control'

    .form-group
      = f.label :description, (t 'description')
      = f.text_area :description, placeholder: (t 'descriptiontips'), class: 'form-control'

    -#Leave this out for now. Only add it once we expand outside of GDL.
    -#.form-group
    -#  .row
    -#    .col
    -#      = f.label :city, (t 'city')
    -#      = f.text_field :city, class: 'form-control'
    -#    .col
    -#      = f.label :state, (t 'stateprovince')
    -#      = f.select :state, '---', {}, class: 'form-control'
    -#    .col  
    -#      = f.label :country, (t 'country')
    -#      = f.select :country, GENERALCFG['countrydata'].map{|x| x['name']}, {}, {class: 'form-control', selected: "Mexico", onChange: "populateregions();"}
  

    .form-group
      = f.label :image, (t 'uploadphoto')
      = f.file_field :image, class: 'form-control-file'
  
  
    .form-group.text-center
      = f.button buttoncaption, class: 'btn btn-success', data: {disable_with: debouncecaption}


#countrydata{data: GENERALCFG['countrydata'].to_json.html_safe}

app/views/listings/_grid-display.html.haml
-@listings.where(filtercondition).in_groups_of(4, false).each do |group|
  .row
    -group.each do |listing|
      .col-md-3
        .card.mt-3.w-auto
          =display_card_image(listing)
          .card-body
            %h5.card-title
              =listing.title
            %p.card-text.text-justify 
              =listing.description 
            %p.text-center.pt-2
              =link_to (t 'viewdetails'), listing, class: "btn btn-primary"


 

app/views/listings/_list-display.html.haml
.table-responsive
  %table.table.text-left
    %thead
      %tr
        %th 
        %th 
        %th 
        %th

    %tbody
      - @listings.where(filtercondition).each do |listing|
        %tr
          %td
            =display_image(listing)  
          %td= listing.title
          %td= listing.description
          %td.text-center.w-25.align-middle
            -if (current_user && current_user.admin?)
              =link_to "<i class = \"fas fa-eye mr-2\"></i>#{t 'show'}".html_safe, listing, class: "btn btn-primary btn-sm"
              =link_to "<i class = \"far fa-edit mr-2\"></i>#{t 'edit'}".html_safe, edit_listing_path(listing), class: "btn btn-secondary btn-sm"
              =link_to "<i class = \"far fa-trash-alt mr-2\"></i>#{t 'delete'}".html_safe, listing, method: :delete, data: {confirm: (t 'areyousuredeletelisting')}, class: "btn btn-danger btn-sm"
            -else
              =link_to (t 'viewdetails'), listing, class: "btn btn-primary"

app/views/listings/_listing.html.haml
%tr
  %td 
    =display_image(listing)  
  %td= listing.title
  %td= listing.description
  %td= listing.created_at.strftime("%d/%m/%Y")
  %td= listing.expires.strftime("%d/%m/%Y")
  %td.text-center.w-25.align-middle
    =link_to "<i class = \"fas fa-eye mr-2\"></i>#{t 'show'}".html_safe, listing, class: "btn btn-green btn-sm"
    =link_to "<i class = \"far fa-edit mr-2\"></i>#{t 'edit'}".html_safe, edit_listing_path(listing), class: "btn btn-primary btn-sm"
    =link_to "<i class = \"far fa-trash-alt mr-2\"></i>#{t 'delete'}".html_safe, listing, method: :delete, data: {confirm: (t 'areyousuredeletelisting')}, class: "btn btn-danger btn-sm"

app/views/listings/_smallnavtabs.html.haml
%ul#sbpills-tab.nav.nav-pills.small-navpills.justify-content-start.my-3{:role => "tablist"}

  %li.nav-item
    %a#pills-sell-tab.nav-link.active.smallerpill{"aria-controls" => "pills-sell", "aria-selected" => "true", "data-toggle" => "pill", :href => "#pills-sell", :role => "tab"} 
      =t 'offering'
  %li.nav-item
    %a#pills-buy-tab.nav-link.smallerpill{"aria-controls" => "pills-buy", "aria-selected" => "false", "data-toggle" => "pill", :href => "#pills-buy", :role => "tab"} 
      =t 'seeking'

#sbpills-tabContent.tab-content
  #pills-sell.tab-pane.fade.show.active{"aria-labelledby" => "pills-sell-tab", :role => "tabpanel"}
    .table-responsive
      %table.table.text-left
        %thead
          %tr
            %th 
            %th 
              = t 'tabletitle'
            %th 
              =t 'tabledescription'
            %th
              =t 'created'
            %th
              =t 'expires'
            %th.text-center 
              =t 'manage'
        %tbody
          = yield :tabsell
  #pills-buy.tab-pane.fade{"aria-labelledby" => "pills-buy-tab", :role => "tabpanel"}
    .table-responsive
      %table.table.text-left
        %thead
          %tr
            %th 
            %th 
              = t 'tabletitle'
            %th 
              =t 'tabledescription'
            %th
              =t 'created'
            %th
              =t 'expires'
            %th.text-center 
              =t 'manage'
        %tbody
          = yield :tabbuy

app/views/listings/edit.html.haml
=content_for :title, (t 'editlisting')
.form-wrapper.w-75
  %h3.text-center.mb-5 
    =t ('editlisting')

  = render 'form', buttoncaption: (t 'update'), debouncecaption: (t 'updating')

.text-center
  = link_to (t 'show'), @listing
  \|
  = link_to (t 'back'), :back

app/views/listings/index.html.haml
= render 'layouts/carousel'

.container-fluid.px-5

  = render 'layouts/listingnavtabs'

app/views/listings/index2.html.haml
.listing-wrapper

  %h1 Indice de Anuncios

  %table.table.text-left
    %thead
      %tr
        %th Foto
        %th Title
        %th Description
        %th
        %th
        %th

    %tbody
      - @listings.each do |listing|
        %tr
          %td
            =display_image(listing)  
          %td= listing.title
          %td= listing.description
          %td= link_to 'Show', listing
          %td= link_to 'Edit', edit_listing_path(listing)
          %td= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' }

%br

.text-center
  = link_to 'Crear un anuncio', new_listing_path

app/views/listings/new.html.haml
= content_for :title, (t 'createad')
.form-wrapper

  %h3.text-center.mb-5 
    =t 'publishad'

  = render 'form', buttoncaption: (t 'publishmyad'), debouncecaption: (t 'publishing')

.text-center
  = link_to (t 'back'), :back

app/views/listings/show.html.haml
=content_for :title, (t 'showlisting')

.listing-wrapper

  .row
    .col-lg-8
      .card.mt-3
        .card-header.bg-blue.py-1
          %h5.card-title.text-center.mb-0.text-white
            = @listing.title
            
        .card-body
          .text-justify
            = @listing.description
          -if @listing.image.attached?
            =image_tag @listing.image, class: 'img-fluid mt-4'
    
    .col-lg-4
      .card.mt-3
        .card-header.bg-primary.py-1
          %h5.card-title.text-center.mb-0.text-white
            = t ('contactlistingowner') 
        .card-body
          .text-justify    
            =render 'contact/contact_form', buttoncaption: (t 'sendmsg'), debouncecaption: (t 'sending'), listingid: @listing.id


.text-center
  -if current_user && (@listing.owned_by?(current_user) || current_user.admin?)
    = link_to (t 'edit'), edit_listing_path(@listing)
    \|
  = link_to (t 'back'), :back