config/routes.rb
Rails.application.routes.draw do
  

  devise_for :users, only: :omniauth_callbacks, controllers: {omniauth_callbacks: 'user/omniauth_callbacks'}

  scope "(:locale)", :locale => /#{I18n.available_locales.join("|")}/ do  


    devise_for :users, skip: [:registrations, :omniauth_callbacks], controllers: {confirmations: 'user/confirmations'}, 
                        path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register', 
                                               password: 'password', confirmation: 'account-activation'}
    
    devise_scope :user do      
      # registrations
      put    '/users',  to: 'user/registrations#update'
      delete '/users',  to: 'user/registrations#destroy'
      post   '/users',  to: 'user/registrations#create'
      get    '/register', to: 'user/registrations#new',    as: :new_user_registration
      get    '/users/:id/edit',  to: 'user/registrations#edit',   as: :edit_user_registration
      patch  '/users',  to: 'user/registrations#update', as: :user_registration
      get    '/users/cancel', to: 'user/registrations#cancel', as: :cancel_user_registration 
    end


    resources :users, only: [:show]
    resources :listings
    resources :buys, controller:"listings", type:"Buy"
    resources :sells, controller:"listings", type:"Sell"
    resources :contactmsg, only: [:listing_contact]

    post '/contact', to: 'contacts#listing_contact'


    root 'listings#index'

    get '/about' => "pages#about"
    

  end #locale scope
  
end

app/views/layouts/_banner.html.haml
.container-fluid.px-0
  .banner
    .bannerheading.pt-5
      =yield(:title)

app/views/layouts/_carousel.html.haml
#mainslider.carousel.slide.carousel-fade{"data-ride" => "carousel"}
  %ol.carousel-indicators
    %li.active{"data-slide-to" => "0", "data-target" => "#mainslider"}
    %li{"data-slide-to" => "1", "data-target" => "#mainslider"}
    %li{"data-slide-to" => "2", "data-target" => "#mainslider"}
    %li{"data-slide-to" => "3", "data-target" => "#mainslider"}
  .carousel-inner
    .carousel-item.t15.active
      = image_tag "flowers.jpg", class: 'd-block w-100'
      .carousel-caption.caption1
        %h1 
          =t 'carousel.wanttohelp'
       
    
    .carousel-item.t10
      =image_tag "lemur.jpg", class: 'd-block w-100'
      .carousel-caption.caption2
        %h1 
          =t 'carousel.wehelpreuse'
    
    .carousel-item.t10
      =image_tag "mountain.jpg", class: 'd-block w-100'
      .carousel-caption.caption3
        %h1 
          =t 'carousel.yourjunkisuseful'

    .carousel-item
      =image_tag "mountainlake.jpeg", class: 'd-block w-100'
      .carousel-caption.caption4
        %h1 
          =t 'carousel.advertisewithus_html'

  %a.carousel-control-prev{"data-slide" => "prev", :href => "#mainslider", :role => "button"}
    %span.carousel-control-prev-icon{"aria-hidden" => "true"}
    %span.sr-only =t 'previous'
  %a.carousel-control-next{"data-slide" => "next", :href => "#mainslider", :role => "button"}
    %span.carousel-control-next-icon{"aria-hidden" => "true"}
    %span.sr-only =t 'next'

:javascript
  $(document).ready(function(){
  
    $('#mainslider').carousel({
      interval: 5000
    });

  })

app/views/layouts/_footer.html.haml
%footer.bottom.bg-midgrey
  %nav.navbar.navbar-dark.navbar-expand.mt-0
    %ul.navbar-nav.ml-auto
      %li.nav-item
        = link_to "Help", "#", class: 'nav-link'
      %li.nav-item
        = link_to "About", "#", class: 'nav-link'
      %li.nav-item
        = link_to "Terms of Service", "#" , class: 'nav-link'

app/views/layouts/_gridlisticons.html.haml
%ul.nav.nav-pills.justify-content-end.mb-3.fixed-navpills{:role => "tablist", :id=> "pills-tab_#{idno}"}
    
  %li.nav-item
    %a.nav-link.active{"aria-controls" => "pills-list_2", "aria-selected" => "true", "data-toggle" => "pill", :href => "#pills-list_#{idno}", :role => "tab", :id => "pills-list-tab_2"} 
      %i.fa.fa-list
  %li.nav-item
    %a.nav-link{"aria-controls" => "pills-grid_#{idno}", "aria-selected" => "false", "data-toggle" => "pill", :href => "#pills-grid_#{idno}", :role => "tab", :id => "pills-grid-tab_#{idno}"} 
      %i.fa.fa-th

.tab-content{:id => "pills-tabContent2"}
  .tab-pane.fade.show.active{"aria-labelledby" => "pills-list-tab_#{idno}", :role => "tabpanel", :id => "pills-list_#{idno}"}
    = render 'listings/list-display', filtercondition: filtercondition
  .tab-pane.fade{"aria-labelledby" => "pills-grid-tab_#{idno}", :role => "tabpanel", :id => "pills-grid_#{idno}"}
    = render 'listings/grid-display', filtercondition: filtercondition

app/views/layouts/_listingnavtabs.html.haml
%ul#sbpills-tab.nav.nav-pills.justify-content-start.my-3.pl-1{:role => "tablist"}

  %li.nav-item
    %a#pills-sell-tab.nav-link.active.largerpill{"aria-controls" => "pills-sell", "aria-selected" => "true", "data-toggle" => "pill", :href => "#pills-sell", :role => "tab"} 
      =t 'offering'
  %li.nav-item
    %a#pills-buy-tab.nav-link.largerpill{"aria-controls" => "pills-buy", "aria-selected" => "false", "data-toggle" => "pill", :href => "#pills-buy", :role => "tab"} 
      =t 'seeking'

#sbpills-tabContent.tab-content
  #pills-sell.tab-pane.fade.show.active{"aria-labelledby" => "pills-sell-tab", :role => "tabpanel"}
    -if mobile_device !="mobile"
      = render 'layouts/gridlisticons', filtercondition: {type: "Sell"}, idno: '1'
    -else
      = render 'listings/grid-display', filtercondition: {type: "Sell"}
  #pills-buy.tab-pane.fade{"aria-labelledby" => "pills-buy-tab", :role => "tabpanel"}
    -if mobile_device != "mobile"
      = render 'layouts/gridlisticons', filtercondition: {type: "Buy"}, idno: '2'
    -else
      = render 'listings/grid-display', filtercondition: {type: "Buy"}
    

app/views/layouts/_midfooter.html.haml
.container-fluid.px-0
  .midfooter
    .row
      .col-md-4.midfooterblock
     
        %h5.block-title
          =t 'searcher'
        %p.block-body
          Search here

        %h5.block-title.mt-5.mb-3
          =t 'followus'
        %p.block-body
          =link_to '<i class = "fab fa-facebook fa-2x mr-3"></i>'.html_safe, GENERALCFG['socialmedia']['facebook']
          =link_to '<i class = "fab fa-twitter fa-2x mr-3"></i>'.html_safe, GENERALCFG['socialmedia']['twitter']
          =link_to '<i class = "fab fa-instagram fa-2x"></i>'.html_safe, GENERALCFG['socialmedia']['instagram']
      
      .col-md-4.midfooterblock
        %h5.block-title
          =t 'dontthrowit'
        %p.block-body
          =t 'wanttohelp'
          =link_to (t 'advertisehere'), new_listing_path
          =t 'toseeif'
       
      .col-md-4.midfooterblock
        %h5.block-title
          =t 'latesttweets'
        %p.block-body
          <a class="twitter-timeline" data-width="400" data-dnt="true" data-height="300" data-theme="dark" href="https://twitter.com/TlacuacheOrg?ref_src=twsrc%5Etfw">Tweets by TlacuacheOrg</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

app/views/layouts/_navbar.html.haml
%header
  %nav.top.navbar.navbar-expand-lg.py-2.px-4.navbar-dark.bg-black
    = link_to image_tag('tlacuache52px.png', alt: "El Tlacuache", class: 'navbar-brand'), main_app.root_path
  

    
    %button.navbar-toggler.navbar-toggler-right{"aria-controls" => "navbarToggler", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarToggler", "data-toggle" => "collapse", :type => "button"}
      .navbar-toggler-icon
    #navbarToggler.collapse.navbar-collapse
      %ul.navbar-nav.ml-auto
        = yield :navlinks


        
        
        %li.nav-item.dropdown.ldropdown
          %a#langdropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#"}
            =t 'lname' 
          .dropdown-menu.dropdown-menu-right{"aria-labelledby" => "langdropdown"}
            - I18n.available_locales.without(I18n.locale).each do |x|
              =link_to t('lname', locale: x), {locale: x}, {class: 'dropdown-item ldropdown'}

app/views/layouts/_navbarlinks.html.haml
= content_for :navlinks do
  - if user_signed_in?
    = render 'layouts/signedinnavbarlinks'
  - else
    %li.nav-item.pr-2
      = link_to (t 'aboutus'), about_path, class: 'nav-link'
    %li.nav-item.pr-2
      = link_to "<i class = \"fa fa-plus-circle mr-2\"></i>#{t 'navlinks.advertisehere'}".html_safe, new_listing_path, class: 'nav-link btn btn-green'
    %li.nav-item.pl-2
      = link_to (t 'navlinks.loginregister'), new_user_session_path, class: 'nav-link btn btn-light'

app/views/layouts/_searchbar.html.haml
= form_tag(search_page_path, :method => "get", |
  class: 'navbar-form navbar-left') do         |
  .input-group
    = search_field_tag :search, params[:search], placeholder: "Search", class: "form-control"
    .input-group-btn
      = button_tag "", :class => 'btn btn-info glyphicon glyphicon-search',:name => nil

app/views/layouts/_signedinnavbarlinks.html.haml
%li.nav-item.pr-3
  =link_to (t 'navlinks.myprofile'), user_path(current_user), class: "nav-link"
%li.nav-item.pr-2
  = link_to "<i class = \"fa fa-plus-circle mr-2\"></i>#{t 'navlinks.advertisehere'}".html_safe, new_listing_path, class: 'nav-link btn btn-green'
%li.nav-item
  = link_to (t 'navlinks.logout'), destroy_user_session_path, method: :delete, class: "nav-link"

app/views/layouts/_stdheader.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %meta{:content => "on", :name => "twitter:dnt"}/

    / -- Social Media and sharing
    %meta{:property => "og:title", :content => "El Tlacuache"}
    %meta{:property => "og:type", :content => "website"}
    %meta{:property => "og:url", :content => "https://www.tlacuache.org"}
    %meta{:property => "og:image", :content => image_url("flowers.jpg")}
    %meta{:content => "@Tlacuacheorg", :name => "twitter:site"}/

    
    %title El Tlacuache
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    %noscript
      %meta{:content => "2;url=/nojavascript.html?locale=#{I18n.locale}", "http-equiv" => "refresh"}


    

:javascript
  window['_fs_debug'] = false;
  window['_fs_host'] = 'fullstory.com';
  window['_fs_script'] = 'edge.fullstory.com/s/fs.js';
  window['_fs_org'] = 'S3TBN';
  window['_fs_namespace'] = 'FS';
  (function(m,n,e,t,l,o,g,y){
      if (e in m) {if(m.console && m.console.log) { m.console.log('FullStory namespace conflict. Please set window["_fs_namespace"].');} return;}
      g=m[e]=function(a,b,s){g.q?g.q.push([a,b,s]):g._api(a,b,s);};g.q=[];
      o=n.createElement(t);o.async=1;o.crossOrigin='anonymous';o.src='https://'+_fs_script;
      y=n.getElementsByTagName(t)[0];y.parentNode.insertBefore(o,y);
      g.identify=function(i,v,s){g(l,{uid:i},s);if(v)g(l,v,s)};g.setUserVars=function(v,s){g(l,v,s)};g.event=function(i,v,s){g('event',{n:i,p:v},s)};
      g.shutdown=function(){g("rec",!1)};g.restart=function(){g("rec",!0)};
      g.log = function(a,b){g("log",[a,b])};
      g.consent=function(a){g("consent",!arguments.length||a)};
      g.identifyAccount=function(i,v){o='account';v=v||{};v.acctId=i;g(o,v)};
      g.clearUserCookie=function(){};
      g._w={};y='XMLHttpRequest';g._w[y]=m[y];y='fetch';g._w[y]=m[y];
      if(m[y])m[y]=function(){return g._w[y].apply(this,arguments)};
  })(window,document,window['_fs_namespace'],'script','user');

app/views/layouts/application.html.haml
= render 'layouts/stdheader'
= render 'layouts/navbarlinks'
= render 'layouts/navbar'
  

.container-fluid

  -flash.each do |name, msg|
    = content_tag :div, class: [:alert, 'alert-dismissible', 'fade', 'show', alert_for(name)] do
      = msg
      %button.close{"aria-label" => "Close", "data-dismiss" => "alert", :type => "button"}
        %span{"aria-hidden" => 'true'}
          &times;
= yield

.mt-5
  =render 'layouts/midfooter'
= render 'layouts/footer'

app/views/layouts/nobanner.html.haml
= render 'layouts/stdheader'
= render 'layouts/navbarlinks'
= render 'layouts/navbar'
  

.container-fluid

  -flash.each do |name, msg|
    = content_tag :div, class: [:alert, 'alert-dismissible', 'fade', 'show', alert_for(name)] do
      = msg
      %button.close{"aria-label" => "Close", "data-dismiss" => "alert", :type => "button"}
        %span{"aria-hidden" => 'true'}
          &times;
= yield

.mt-5
  =render 'layouts/midfooter'
= render 'layouts/footer'